Update git version tag on local builds.
shader-slang/slang pull request #2776
Opened 2023-04-05 01:47 UTC by csyonghe

We use git tag for release builds on github but not local builds.
This enables using the result of git describe as version string for local builds.

2023-04-06 20:09 UTC, jsmall-nvidia commented on slang-tag-version.h
> +#define SLANG_TAG_VERSION "v0.27.6-9-ga05e12fc"
Shouldn't this stay as unknown, or be removed from the project?

2023-04-06 20:10 UTC, jsmall-nvidia requested changes
The slang-tag-version.h seems to be in .gitignore, but is still part of the project?

2023-04-13 19:36 UTC, csyonghe commented
The problem is that slang-tag-version.h is still needed for people who pull and build on linux because we haven't integrated generation of this file as a part of linux build. I am not sure if premake's prebuild event will work there.

2023-04-14 00:50 UTC, expipiplus1 commented
For other shells, it could be something like this (bananas that the powershell version is so incredibly verbose)

```lua
    filter { "not system:windows" } 
        prebuildcommands {
            'printf "#define SLANG_TAG_VERSION \\"$$(git describe --tags)\\"\\n" > ' .. path.getabsolute("slang-tag-version.h")
        }
```

The prebuild event seems to work fine, although it's extra noise on every build :/

It is however displeasing that the format of this header is duplicated here and in the powershell script. Premake doesn't seem to have any support for template files, but if you could get the powershell equivalent of the (untested) following then I think that'd be neater.

```lua    
        prebuildcommands {
            'sed -e s/@VCS_TAG@/$$(git describe --tags)/' .. 
				        '<' .. path.getabsolute("slang-tag-version.h.in")
				        '>' .. path.getabsolute("slang-tag-version.h")
        }
```

(with slang-tag-version.h.in)
```c
#define SLANG_TAG_VERSION "@VCS_TAG@"
```

2023-04-14 00:57 UTC, expipiplus1 commented
Also note that, as implemented without a fallback, this makes `git` a build dependency and prevents building from a source tarball.

2023-04-14 01:07 UTC, csyonghe commented
I kind of want to use C++17 has_include feature to just allow things to compile without the header to exist. On windows the power shell script is set to not return failure if any of the command fails, so strictly there is not a dependency on git.

2023-04-14 03:08 UTC, expipiplus1 commented
```lua
    filter { "not system:windows" } 
        prebuildcommands {
            'printf "#define SLANG_TAG_VERSION \\"$$(git describe --tags || printf unknown)\\"\\n" > ' .. path.getabsolute("slang-tag-version.h")
        }
```

This should be tolerant of missing git

2023-05-12 22:34 UTC, closed without merging