Separating slang-test in CI for emit-spirv-via-glsl
shader-slang/slang pull request #4665
Opened 2024-07-16 21:45 UTC by jkwak-work

When CI test failes, we expect to see the error messages at the end of each section of CI testing result. But currently when "emit-spirv-via-glsl" fails, the error messages appear in the middle, which lead us to believe that there is no errors when you look only at the end of the result.

This commit separates out the "emit-spirv-via-glsl" case to make the error message more visiable.

2024-07-16 23:12 UTC, jkwak-work commented
It appears that an option "-server-count 8" for slang-test was intentionally missing from Linux/macOS platforms.
I wonder if "-use-test-server" should also be removed from those platforms.

2024-07-17 08:54 UTC, expipiplus1 requested changes
lgtm aside from comments.

Although it might be neater to just synthesize the "via glsl" tests in the same way we synthesize cuda tests, that way we can dispense with having to run slang-test twice at all

2024-07-17 08:54 UTC, expipiplus1 commented on .github/workflows/ci.yml
> +          if [[ "${{matrix.full-gpu-tests}}" == "true" ]]; then
This conditional can be raised to be an `if` field alongside `name` and `run` now

2024-07-17 08:54 UTC, expipiplus1 commented on .github/workflows/ci.yml
> +          failed=0
No need for the failed variable tracking now

2024-07-17 08:54 UTC, expipiplus1 commented on .github/workflows/ci.yml
>                failed=1
No need for the failed variable tracking now

2024-07-18 03:38 UTC, expipiplus1 commented on .github/workflows/ci.yml
> +          if [[ "${{matrix.full-gpu-tests}}" == "true" ]]; then
I meant in the yaml having `if: matrix.full-gpu-tests == 'true'`

2024-07-18 23:28 UTC, merged