wgsl: Fix field semantics even if input struct doesn't need flattening
shader-slang/slang pull request #5642
Opened 2024-11-22 11:48 UTC by aleino-nv

This fixes an issue where location indices of stage inputs were repeated

https://github.com/shader-slang/slang/issues/5633

2024-11-22 22:55 UTC, csyonghe approved these changes

2024-11-22 23:25 UTC, jkwak-work requested changes
I feel uncomfortable with this change.

The code is copied exactly from slang-ir-metal-legalize.cpp
And with this PR, WGPU side works but Metal side is failing.

I suggest to investigate why Metal is failing and fix it properly before merging this change.

2024-11-22 23:29 UTC, csyonghe commented
I feel like metal needs the same treatment.

2024-11-23 14:44 UTC, jkwak-work commented on source/slang/slang-ir-wgsl-legalize.cpp
> +                fixFieldSemanticsOfFlatStruct(flattenedStruct);
If this function is going to be called even when it is not flattened, the name of the function may need to change to match

2024-11-23 14:46 UTC, jkwak-work commented
> I feel like metal needs the same treatment.

Yes, that must be it.

2024-11-23 14:46 UTC, jkwak-work approved these changes

2024-11-25 06:04 UTC, aleino-nv commented
> > I feel like metal needs the same treatment.
> 
> Yes, that must be it.

2024-11-25 08:15 UTC, merged

2024-11-25 10:27 UTC, aleino-nv commented
> > I feel like metal needs the same treatment.
> 
> Here is a PR #5666

Ok the PR fails, I filed https://github.com/shader-slang/slang/issues/5667.
The render0 test is also broken for Metal, so it's probably best to fix that one first, and then enable this test.