Add backtraces to examples
shader-slang/slang pull request #5973
Opened 2024-12-31 13:51 UTC by aleino-nv

- Add backtrace-printing support for Windows, for both `main` and `WinMain` examples.
- For `WinMain` example programs, redirect stdout to `stdout-[example].txt` and print that in CI if it's found.

This helps to address #5520.

2024-12-31 13:51 UTC, aleino-nv commented
/format

2025-01-02 06:11 UTC, aleino-nv commented on examples/stacktrace-windows/common.cpp
> +#include <dbghelp.h>
`windows.h` must be included before dbghelp.h. Need to figure out a way to make formatting not reorder the headers like this.

2025-01-02 11:14 UTC, expipiplus1 requested changes

2025-01-02 11:14 UTC, expipiplus1 commented on examples/stacktrace-windows/common.cpp
> +// NOTE: This function is not thread-safe, due to usage of StackWalk64 and static buffers.
We should use a mutex here to make this function reentrant

2025-01-02 13:50 UTC, aleino-nv commented on examples/stacktrace-windows/common.cpp
> +// dbghelp.h needs to be included after windows.h
This can also be done by just putting the dbghelp.h include in it's own block surrounded by empty lines.

2025-01-02 15:57 UTC, aleino-nv commented
/format

2025-01-03 06:45 UTC, aleino-nv commented on examples/stacktrace-windows/common.cpp
> +// NOTE: This function is not thread-safe, due to usage of StackWalk64 and static buffers.
It's currently only called from the main thread.

I suppose it's possible some other thread will call these dbghelp API's, is that the concern?

If so I would prefer it if the function was "externally synchronized" i.e. the mutex is around the call site.

2025-01-03 07:43 UTC, aleino-nv commented on tools/platform/window.h
> -        GFX_DUMP_LEAK                                \
`GFX_DUMP_LEAK` should also be expanded in the new main wrapper.

2025-01-03 07:54 UTC, aleino-nv commented
/format

2025-01-03 08:38 UTC, aleino-nv commented
/format

2025-01-03 22:57 UTC, csyonghe approved these changes

2025-01-08 06:30 UTC, merged